### ISSUE TITLE
contrast calculation is not always visible without scrolling

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Contrast-Finder#148]
## Observed behaviour
in french by @ffoodd
> (...) le résultat du calcul de contraste ne soit pas toujours visible sans scroller. Je trouverais confortable de n’avoir à scroller que quand on cherche une valeur alternative

the result of the contrast calculation is not always visible without scrolling. I'd find it comfortable to have to scroll only when you're looking for an alternative value.

**Comment by dzc34** [comment]
fixed 
@ffoodd, what do you think?

![](https://user-images.githubusercontent.com/6709977/39085461-dbe3f11a-4582-11e8-92a7-a2e0ea0aa984.png)

------------------

![](https://user-images.githubusercontent.com/6709977/39085462-dc0770ea-4582-11e8-9986-adbb2cfcb21f.png)
```
<div id="currentRatio" aria-live="off" class="col-lg-1">
   <div id="isValidRatio"> 
      <img id="isValidRatio_Passed" src="ico-passed-m.png" 
           alt="Le contraste de vos couleurs est suffisant."
           class="hidden">
      <img id="isValidRatio_Failed" src="ico-failed-m.png" 
           alt="Le contraste de vos couleurs est insuffisant."> 
    </div>
   <div id="currentRatioTxt">
      <span class="sr-only">Ratio actuel :</span> 
      <output form="colorModel" 
              for="ratio background-input foreground-input"
              name="currentRatioData" 
              id="currentRatioData">1.02</output> 
    </div>
</div>
```

**Comment by ffoodd** [comment]
It's perfect! 

Thanks a lot :grinning:
