### ISSUE TITLE
i18n - Missing Spanish translation strings: page.about.*

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Contrast-Finder#244]
Missing Spanish translation strings 
on this following URL: https://app.contrast-finder.org/about.html?lang=es

i18n file:
 [/webapp/src/main/resources/i18n/**contrast-finder_utf8_es.properties**](https://github.com/Asqatasun/Contrast-Finder/blob/develop/webapp/src/main/resources/i18n/contrast-finder_utf8_es.properties#L78) (between line 78 and line 102)
```properties
# page.result-error.titleTag=Error
# page.about.titleTag=About Contrast-Finder
# page.about.title=About <em lang="en">Contrast-Finder</em>
# page.about.links=You will find more information in english on the project website:(...)
# page.about.fileList.title=Additional files
# page.about.build.title=Build info
# page.about.build.version=version:
# page.about.build.gitBranch=git branch:
# page.about.build.gitCommit=git commit:
# page.about.build.build=Build:
# page.about.build.date=date:
# page.about.build.id=ID:
# page.about.build.platform=Platform:
# page.about.availableLanguages=Available languages
```

**Comment by dzc34** [comment]
ping @davidjr82, if you have some time ?

**Comment by davidjr82** [comment]
PR in #247 
Updated also some old strings.

**Comment by dzc34** [comment]
PR merged.  
Thanks again for your help.
