### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by scottaohara** [Asqatasun/Contrast-Finder#83]
## Observed behaviour
There is a spelling error when displaying a valid contract color combination. The text reads: "The choosen colors are already good" but "chosen" has an extra "o"

![screen shot 2017-08-01 at 7 18 37 am](https://user-images.githubusercontent.com/4152514/28823042-badf131e-7689-11e7-810e-cf7fc98359e4.jpg)

## Expected behaviour
Correct "choosen" to "chosen"

## Steps to reproduce the behaviour
Input a valid contract color combination

## Your configuration
Latest FireFox on MacOS
Text color rgb(255,105,121)
Background color #333
Minimum ratio 4.5

**Comment by mfaure** [comment]
ouch, nice catch @scottaohara !

Work in progress in #84

**Comment by dzc34** [comment]
Fixed in develop branch. Will be included in the next minor version.
Thank @scottaohara for your bug report and @mfaure for the fix.
