### ISSUE TITLE
No result given --> impossible so not serious

### ISSUE THREAD

**Issue by mfaure** [Asqatasun/Contrast-Finder#91]
## Observed behaviour

* foreground = white
* background = rgb(105, 209, 0);
* ratio = 4.5
* algo = close to initial color
* result = no result (!)

## Expected behaviour

I would like to have a result. No result implies that not any green in the world could be used with white text, which is wrong.

Suggestion: if the first algorithm (close to initial color) fails, then switch back to the other one (range of color), event if it take 5ms more !

**Comment by dzc34** [comment]
added to #161 and closed
